### ISSUE TITLE
MMOKitchen broken through PlateUp! Mod manager because it can't find kitchenlib-bepis

### ISSUE THREAD

**Issue by jeid64** [StarFluxMods/MMOKitchen#4]
Howdy, installing MMOKitchen v.0.1.4 through the modmanager has you install kitchenlib-bepinex v.0.2.6, but this version of kitchenlib is broken. MMOKitchen complains it can't find the DLL. We downloaded kitchenlib-bepinex.dll of v.0.2.2 off the Github release and replaced the DLL for it, and MMOKitchen booted fine, so it seems like something with the newer releases of kitchenlib isn't getting matched.

**Comment by StarFluxGames** [comment]
@jeid64 At the moment the latest version of MMO Kitchen and KitchenLib are compatible with each other, although the versions on the Mod Manager haven't been updated.

As Steam Workshop support is extremely close I've decided to stop updating the Mod Manager, and begin to phase it out as it won't be needed.
